/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ng.org.gradle.java;

import ng.org.gradle.jvm.model.JvmLibraryFeature;
import ng.org.gradle.software.model.LibraryComponent;
import ng.org.gradle.software.model.Model;
import org.gradle.api.Project;
import org.gradle.api.Plugin;

import java.util.Arrays;

/*
Component
    Coordinates
Feature
    Variant
        Name
        Coordinates?
        Capabilities
        Attributes
        Artifact
        Dependencies (+constraints)

---
Metadata rules?
Variant rules?

---

Software Development Jargon

what are elements?

- Libraries
    - API elements
    - Runtime elements
    - Documentation
    - Sources
    - Reports (code quality?)
    - Related components?

- Applications
    - Installation elements
    - Distribution elements
    - Runtime elements
    - Documentation
    - Sources
    - Reports (code quality?)
    - Related components

Tests are components. Tests are applications.
Test fixtures are components. Test fixtures are libraries.

Maybe later
- Platforms
    - API elements
    - Runtime elements
    - Reports (CVE?)
    - Related components

---
// foo/build.gradle
// apply java-library

components {
    foo(LibraryComponent) {
        features {
            main(JvmLibraryFeature) {
                targetJdks = [ 8, 15 ]
                sources {
                    java {
                        srcDir "src/main/java"
                    }
                }
                dependencies {
                    api "..."
                    implementation "..."
                }
                targets {
                    main8(JvmLibraryTarget) {
                        sources {
                            java {
                                srcDir "src/main8/java"
                            }
                        }
                        dependencies {
                            api "..."
                            implementation "..."
                        }
                    }
                    main15(JvmLibraryTarget) {
                        // ...
                    }
                }
                variants {
                    // for 8
                    apiElements8(JavaApi) {
                    }
                    runtimeElements8(JavaRuntime) {
                    }
                    sourceElements8(JavaSources) {
                    }
                    javadocElements8(JavaDocumentation) {
                    }
                    // for 15 too
                }
            }
        }
    }
}

 */
/**
 * A simple 'hello world' plugin.
 * java-library = software-library + jvm-library + jvm-ecosystem + java-language
 * java-library adds java extension to sources adds JavaApi variants?
 */
public abstract class JavaLibraryPlugin implements Plugin<Project> {
    public void apply(Project project) {
        project.getPluginManager().apply("ng.org.gradle.jvm-library");
        project.getPluginManager().apply("ng.org.gradle.java-language");

        Model model = project.getExtensions().getByType(Model.class);
        model.getComponents().withType(LibraryComponent.class).named(project.getName(), component -> {
            component.getFeatures().withType(JvmLibraryFeature.class).configureEach(feature -> {
                feature.getTargetJdks().convention(Arrays.asList(8, 15));
            });
        });
    }
}
